### ISSUE TITLE
[#32] Header 작업

### ISSUE THREAD

**Issue by seocylucky** [Soongmile/Soongmile-FE#33]
## Issue: ⚒️ FEATURE
공통 컴포넌트인 Header 작업(로그인 상태/비로그인 상태)

## Description
<img width="702" alt="image" src="https://github.com/Soongmile/Soongmile-FE/assets/94633589/93c01331-f452-476a-9fb8-83fd30594633">

## Todo
- [ ] 로고 왼쪽에 배치(누르면 홈페이지로 가도록)
- [ ] 중앙 Nav
   - [ ] 홈
   - [ ] 질문
   - [ ] 포인트
   - [ ] 커피챗
- [ ] 비로그인 상태(로그인, 회원가입)
- [ ] 로그인 상태(알림, 마이페이지, 로그아웃)
