### ISSUE TITLE
[#4] 사이드 바 컴포넌트 제작

### ISSUE THREAD

**Issue by intersoom** [Soongmile/Soongmile-FE#4]
## Description
메인, 마이페이지에 들어갈 사이드바 컴포넌트 제작

## Todo
- [x] 메뉴 리스트 불러오는 방식 결정
- [x] 선택된 사항 볼드
- [x] 메뉴 선택에 따라서 라우팅
